server:
  port: 88
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: tuyou-mqtt
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: dev

mybatisPlus:
  mapperLocations: classpath:mapper/*.xml
  typeEnumsPackage: com.tuyou.mqtt.producer.enumeration.*
  globalConfig:
    dbConfig:
      idType: uuid
      tableUnderline: true
      logicDeleteValue: 1
      logicNotDeleteValue: 0